# Preventing automatic generator tags
exclude: [vendor]
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

# Custom site title for the browser tab
title: Benjamin Wilson | Power Systems Researcher
