title: Benjamin Egyin Wilson
description: Power Systems Researcher | Stability & Optimization
theme: jekyll-theme-cayman # Or your preferred theme
remote_theme: jekyll/jekyll-theme-cayman

# This tells Jekyll where to find your custom CSS
sass:
  style: :compressed
